sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QmsFVvSjzSgSIjvEtZQfcRb9bjRQLrlc9LJ9/El4VNfyExy/HRGB9J9HR99vWp/he/pmaTV0Nn6jNgZ2Dg4mN/Vk9oqLgwi9wghfyIcZTH8WstsWCInSPk0pQ/K+o1No9OUXbZ9hOtUjkypkHMCJl+Qd99WaKsdsTj4wFsJoyykdfxBEHS0InhLYRVojySnoJ2p5So+Pcacti/Kh+gQfbu8isjwen/JLIj4XJ3U/SfXYAcCsDcSEo+LPWsneC7xHF9WTIyrtt5mnLHoZ3aDM91yReweihUMYBk4jwD/8QypDjvyIZczxp2zXkGWsLK1mtm1NE1K5p3irm8i/CF2yWLAvv5LeSAPvRRTYJ9kUSniX1JvILR1oXf3VGRGF8lHxd/AKYRzV4+axqAc4oIH7DD+u0yxoSToe4ygE8VfF85AaQVy9qOVCeyqM7XnFlR3Bq3hyoux4V/DhEs1QBexZyonPECEaThYoqoqZfGWWjPmPNHi8tvyQrZVOwgTv3J9pLnteWbJKPggvnRVNEFUYQ9tKt2KhJAkyICfhUBjlBbV/Hguf9ceBzL9lDij+w+fQsGyuHlw8DjUqaajoANCiJTZflcsxRW3smD2p5UD/IPVcJuDfjrLFvWKIo5gBtrQ5ecUQnQKwi3xnW98rdcclzPpXuSu7OBdujX03LnrNSrI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Memoirs-of-General-William-T.-Sherman---Volume-2_2617
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy